CREATE DATABASE GestionHotelera;

Use GestionHotelera;


CREATE TABLE Habitaciones (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Nombre NVARCHAR(100),
    Torre INT,
    Piso INT,
    NumeroHabitacion INT,
    Disponibilidad BIT
);

CREATE TABLE Reservaciones (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Nombre NVARCHAR(255) NOT NULL,
    PrimerApellido NVARCHAR(255) NOT NULL,
    SegundoApellido NVARCHAR(255),
    CedulaIdentidad NVARCHAR(20) NOT NULL,
    Nacionalidad NVARCHAR(255) NOT NULL,
    Telefono NVARCHAR(20) NOT NULL,
    CorreoElectronico NVARCHAR(255) NOT NULL,
    NombreHotel NVARCHAR(255) NOT NULL,
    Torre INT NOT NULL,
    Piso INT NOT NULL,
    NumeroHabitacion INT NOT NULL
);



INSERT INTO Habitaciones (Nombre, Torre, Piso, NumeroHabitacion, Disponibilidad) VALUES 
('Hotel Continental de Marruecos', 1, 1, 1, 1),
('Hotel Continental de Marruecos', 1, 1, 2, 1),
('Hotel Continental de Marruecos', 1, 1, 3, 1),
('Hotel Continental de Marruecos', 1, 1, 4, 1),
('Hotel Continental de Marruecos', 1, 1, 5, 1),
('Hotel Continental de Marruecos', 1, 1, 6, 1),
('Hotel Continental de Marruecos', 1, 1, 7, 1),
('Hotel Continental de Marruecos', 1, 1, 8, 1),
('Hotel Continental de Marruecos', 1, 1, 9, 1),
('Hotel Continental de Marruecos', 1, 1, 10, 1),
('Hotel Continental de Marruecos', 1, 2, 1, 1),
('Hotel Continental de Marruecos', 1, 2, 2, 1),
('Hotel Continental de Marruecos', 1, 2, 3, 1),
('Hotel Continental de Marruecos', 1, 2, 4, 1),
('Hotel Continental de Marruecos', 1, 2, 5, 1),
('Hotel Continental de Marruecos', 1, 2, 6, 1),
('Hotel Continental de Marruecos', 1, 2, 7, 1),
('Hotel Continental de Marruecos', 1, 2, 8, 1),
('Hotel Continental de Marruecos', 1, 2, 9, 1),
('Hotel Continental de Marruecos', 1, 2, 10, 1),
('Hotel Continental de Marruecos', 1, 3, 1, 1),
('Hotel Continental de Marruecos', 1, 3, 2, 1),
('Hotel Continental de Marruecos', 1, 3, 3, 1),
('Hotel Continental de Marruecos', 1, 3, 4, 1),
('Hotel Continental de Marruecos', 1, 3, 5, 1),
('Hotel Continental de Marruecos', 1, 3, 6, 1),
('Hotel Continental de Marruecos', 1, 3, 7, 1),
('Hotel Continental de Marruecos', 1, 3, 8, 1),
('Hotel Continental de Marruecos', 1, 3, 9, 1),
('Hotel Continental de Marruecos', 1, 3, 10, 1),
('Hotel Continental de Marruecos', 1, 4, 1, 1),
('Hotel Continental de Marruecos', 1, 4, 2, 1),
('Hotel Continental de Marruecos', 1, 4, 3, 1),
('Hotel Continental de Marruecos', 1, 4, 4, 1),
('Hotel Continental de Marruecos', 1, 4, 5, 1),
('Hotel Continental de Marruecos', 1, 4, 6, 1),
('Hotel Continental de Marruecos', 1, 4, 7, 1),
('Hotel Continental de Marruecos', 1, 4, 8, 1),
('Hotel Continental de Marruecos', 1, 4, 9, 1),
('Hotel Continental de Marruecos', 1, 4, 10, 1),
('Hotel Continental de Marruecos', 1, 5, 1, 1),
('Hotel Continental de Marruecos', 1, 5, 2, 1),
('Hotel Continental de Marruecos', 1, 5, 3, 1),
('Hotel Continental de Marruecos', 1, 5, 4, 1),
('Hotel Continental de Marruecos', 1, 5, 5, 1),
('Hotel Continental de Marruecos', 1, 5, 6, 1),
('Hotel Continental de Marruecos', 1, 5, 7, 1),
('Hotel Continental de Marruecos', 1, 5, 8, 1),
('Hotel Continental de Marruecos', 1, 5, 9, 1),
('Hotel Continental de Marruecos', 1, 5, 10, 1),
('Hotel Continental de Marruecos', 2, 1, 1, 1),
('Hotel Continental de Marruecos', 2, 1, 2, 1),
('Hotel Continental de Marruecos', 2, 1, 3, 1),
('Hotel Continental de Marruecos', 2, 1, 4, 1),
('Hotel Continental de Marruecos', 2, 1, 5, 1),
('Hotel Continental de Marruecos', 2, 1, 6, 1),
('Hotel Continental de Marruecos', 2, 1, 7, 1),
('Hotel Continental de Marruecos', 2, 1, 8, 1),
('Hotel Continental de Marruecos', 2, 1, 9, 1),
('Hotel Continental de Marruecos', 2, 1, 10, 1),
('Hotel Continental de Marruecos', 2, 2, 1, 1),
('Hotel Continental de Marruecos', 2, 2, 2, 1),
('Hotel Continental de Marruecos', 2, 2, 3, 1),
('Hotel Continental de Marruecos', 2, 2, 4, 1),
('Hotel Continental de Marruecos', 2, 2, 5, 1),
('Hotel Continental de Marruecos', 2, 2, 6, 1),
('Hotel Continental de Marruecos', 2, 2, 7, 1),
('Hotel Continental de Marruecos', 2, 2, 8, 1),
('Hotel Continental de Marruecos', 2, 2, 9, 1),
('Hotel Continental de Marruecos', 2, 2, 10, 1),
('Hotel Continental de Marruecos', 2, 3, 1, 1),
('Hotel Continental de Marruecos', 2, 3, 2, 1),
('Hotel Continental de Marruecos', 2, 3, 3, 1),
('Hotel Continental de Marruecos', 2, 3, 4, 1),
('Hotel Continental de Marruecos', 2, 3, 5, 1),
('Hotel Continental de Marruecos', 2, 3, 6, 1),
('Hotel Continental de Marruecos', 2, 3, 7, 1),
('Hotel Continental de Marruecos', 2, 3, 8, 1),
('Hotel Continental de Marruecos', 2, 3, 9, 1),
('Hotel Continental de Marruecos', 2, 3, 10, 1),
('Hotel Continental de Marruecos', 2, 4, 1, 1),
('Hotel Continental de Marruecos', 2, 4, 2, 1),
('Hotel Continental de Marruecos', 2, 4, 3, 1),
('Hotel Continental de Marruecos', 2, 4, 4, 1),
('Hotel Continental de Marruecos', 2, 4, 5, 1),
('Hotel Continental de Marruecos', 2, 4, 6, 1),
('Hotel Continental de Marruecos', 2, 4, 7, 1),
('Hotel Continental de Marruecos', 2, 4, 8, 1),
('Hotel Continental de Marruecos', 2, 4, 9, 1),
('Hotel Continental de Marruecos', 2, 4, 10, 1),
('Hotel Continental de Marruecos', 2, 5, 1, 1),
('Hotel Continental de Marruecos', 2, 5, 2, 1),
('Hotel Continental de Marruecos', 2, 5, 3, 1),
('Hotel Continental de Marruecos', 2, 5, 4, 1),
('Hotel Continental de Marruecos', 2, 5, 5, 1),
('Hotel Continental de Marruecos', 2, 5, 6, 1),
('Hotel Continental de Marruecos', 2, 5, 7, 1),
('Hotel Continental de Marruecos', 2, 5, 8, 1),
('Hotel Continental de Marruecos', 2, 5, 9, 1),
('Hotel Continental de Marruecos', 2, 5, 10, 0);


INSERT INTO Habitaciones (Nombre, Torre, Piso, NumeroHabitacion, Disponibilidad)
VALUES
('Hotel Continental de New York', 1, 1, 1, 1),
('Hotel Continental de New York', 1, 1, 2, 1),
('Hotel Continental de New York', 1, 1, 3, 1),
('Hotel Continental de New York', 1, 1, 4, 1),
('Hotel Continental de New York', 1, 1, 5, 1),
('Hotel Continental de New York', 1, 1, 6, 1),
('Hotel Continental de New York', 1, 1, 7, 1),
('Hotel Continental de New York', 1, 1, 8, 1),
('Hotel Continental de New York', 1, 1, 9, 1),
('Hotel Continental de New York', 1, 1, 10, 1),
('Hotel Continental de New York', 1, 2, 1, 1),
('Hotel Continental de New York', 1, 2, 2, 1),
('Hotel Continental de New York', 1, 2, 3, 1),
('Hotel Continental de New York', 1, 2, 4, 1),
('Hotel Continental de New York', 1, 2, 5, 1),
('Hotel Continental de New York', 1, 2, 6, 1),
('Hotel Continental de New York', 1, 2, 7, 1),
('Hotel Continental de New York', 1, 2, 8, 1),
('Hotel Continental de New York', 1, 2, 9, 1),
('Hotel Continental de New York', 1, 2, 10, 1),
('Hotel Continental de New York', 1, 3, 1, 1),
('Hotel Continental de New York', 1, 3, 2, 1),
('Hotel Continental de New York', 1, 3, 3, 1),
('Hotel Continental de New York', 1, 3, 4, 1),
('Hotel Continental de New York', 1, 3, 5, 1),
('Hotel Continental de New York', 1, 3, 6, 1),
('Hotel Continental de New York', 1, 3, 7, 1),
('Hotel Continental de New York', 1, 3, 8, 1),
('Hotel Continental de New York', 1, 3, 9, 1),
('Hotel Continental de New York', 1, 3, 10, 1),
('Hotel Continental de New York', 1, 4, 1, 1),
('Hotel Continental de New York', 1, 4, 2, 1),
('Hotel Continental de New York', 1, 4, 3, 1),
('Hotel Continental de New York', 1, 4, 4, 1),
('Hotel Continental de New York', 1, 4, 5, 1),
('Hotel Continental de New York', 1, 4, 6, 1),
('Hotel Continental de New York', 1, 4, 7, 1),
('Hotel Continental de New York', 1, 4, 8, 1),
('Hotel Continental de New York', 1, 4, 9, 1),
('Hotel Continental de New York', 1, 4, 10, 1),
('Hotel Continental de New York', 1, 5, 1, 1),
('Hotel Continental de New York', 1, 5, 2, 1),
('Hotel Continental de New York', 1, 5, 3, 1),
('Hotel Continental de New York', 1, 5, 4, 1),
('Hotel Continental de New York', 1, 5, 5, 1),
('Hotel Continental de New York', 1, 5, 6, 1),
('Hotel Continental de New York', 1, 5, 7, 1),
('Hotel Continental de New York', 1, 5, 8, 1),
('Hotel Continental de New York', 1, 5, 9, 1),
('Hotel Continental de New York', 1, 5, 10, 1),
('Hotel Continental de New York', 2, 1, 1, 1),
('Hotel Continental de New York', 2, 1, 2, 1),
('Hotel Continental de New York', 2, 1, 3, 1),
('Hotel Continental de New York', 2, 1, 4, 1),
('Hotel Continental de New York', 2, 1, 5, 1),
('Hotel Continental de New York', 2, 1, 6, 1),
('Hotel Continental de New York', 2, 1, 7, 1),
('Hotel Continental de New York', 2, 1, 8, 1),
('Hotel Continental de New York', 2, 1, 9, 1),
('Hotel Continental de New York', 2, 1, 10, 1),
('Hotel Continental de New York', 2, 2, 1, 0),
('Hotel Continental de New York', 2, 2, 2, 0),
('Hotel Continental de New York', 2, 2, 3, 0),
('Hotel Continental de New York', 2, 2, 4, 0),
('Hotel Continental de New York', 2, 2, 5, 0),
('Hotel Continental de New York', 2, 2, 6, 0),
('Hotel Continental de New York', 2, 2, 7, 0),
('Hotel Continental de New York', 2, 2, 8, 0),
('Hotel Continental de New York', 2, 2, 9, 0),
('Hotel Continental de New York', 2, 2, 10, 0),
('Hotel Continental de New York', 2, 3, 1, 0),
('Hotel Continental de New York', 2, 3, 2, 0),
('Hotel Continental de New York', 2, 3, 3, 0),
('Hotel Continental de New York', 2, 3, 4, 0),
('Hotel Continental de New York', 2, 3, 5, 0),
('Hotel Continental de New York', 2, 3, 6, 0),
('Hotel Continental de New York', 2, 3, 7, 0),
('Hotel Continental de New York', 2, 3, 8, 0),
('Hotel Continental de New York', 2, 3, 9, 0),
('Hotel Continental de New York', 2, 3, 10, 0),
('Hotel Continental de New York', 2, 4, 1, 0),
('Hotel Continental de New York', 2, 4, 2, 0),
('Hotel Continental de New York', 2, 4, 3, 0),
('Hotel Continental de New York', 2, 4, 4, 0),
('Hotel Continental de New York', 2, 4, 5, 0),
('Hotel Continental de New York', 2, 4, 6, 0),
('Hotel Continental de New York', 2, 4, 7, 0),
('Hotel Continental de New York', 2, 4, 8, 0),
('Hotel Continental de New York', 2, 4, 9, 0),
('Hotel Continental de New York', 2, 4, 10, 0),
('Hotel Continental de New York', 2, 5, 1, 0),
('Hotel Continental de New York', 2, 5, 2, 0),
('Hotel Continental de New York', 2, 5, 3, 0),
('Hotel Continental de New York', 2, 5, 4, 0),
('Hotel Continental de New York', 2, 5, 5, 0),
('Hotel Continental de New York', 2, 5, 6, 0),
('Hotel Continental de New York', 2, 5, 7, 0),
('Hotel Continental de New York', 2, 5, 8, 0),
('Hotel Continental de New York', 2, 5, 9, 0),
('Hotel Continental de New York', 2, 5, 10, 0)




INSERT INTO Habitaciones (Nombre, Torre, Piso, NumeroHabitacion, Disponibilidad)
VALUES
('Hotel Continental de Roma', 1, 1, 1, 1),
('Hotel Continental de Roma', 1, 1, 2, 1),
('Hotel Continental de Roma', 1, 1, 3, 1),
('Hotel Continental de Roma', 1, 1, 4, 1),
('Hotel Continental de Roma', 1, 1, 5, 1),
('Hotel Continental de Roma', 1, 1, 6, 1),
('Hotel Continental de Roma', 1, 1, 7, 1),
('Hotel Continental de Roma', 1, 1, 8, 1),
('Hotel Continental de Roma', 1, 1, 9, 1),
('Hotel Continental de Roma', 1, 1, 10, 1),
('Hotel Continental de Roma', 1, 2, 1, 1),
('Hotel Continental de Roma', 1, 2, 2, 1),
('Hotel Continental de Roma', 1, 2, 3, 1),
('Hotel Continental de Roma', 1, 2, 4, 1),
('Hotel Continental de Roma', 1, 2, 5, 1),
('Hotel Continental de Roma', 1, 2, 6, 1),
('Hotel Continental de Roma', 1, 2, 7, 1),
('Hotel Continental de Roma', 1, 2, 8, 1),
('Hotel Continental de Roma', 1, 2, 9, 1),
('Hotel Continental de Roma', 1, 2, 10, 1),
('Hotel Continental de Roma', 1, 3, 1, 1),
('Hotel Continental de Roma', 1, 3, 2, 1),
('Hotel Continental de Roma', 1, 3, 3, 1),
('Hotel Continental de Roma', 1, 3, 4, 1),
('Hotel Continental de Roma', 1, 3, 5, 1),
('Hotel Continental de Roma', 1, 3, 6, 1),
('Hotel Continental de Roma', 1, 3, 7, 1),
('Hotel Continental de Roma', 1, 3, 8, 1),
('Hotel Continental de Roma', 1, 3, 9, 1),
('Hotel Continental de Roma', 1, 3, 10, 1),
('Hotel Continental de Roma', 1, 4, 1, 1),
('Hotel Continental de Roma', 1, 4, 2, 1),
('Hotel Continental de Roma', 1, 4, 3, 1),
('Hotel Continental de Roma', 1, 4, 4, 1),
('Hotel Continental de Roma', 1, 4, 5, 1),
('Hotel Continental de Roma', 1, 4, 6, 1),
('Hotel Continental de Roma', 1, 4, 7, 1),
('Hotel Continental de Roma', 1, 4, 8, 1),
('Hotel Continental de Roma', 1, 4, 9, 1),
('Hotel Continental de Roma', 1, 4, 10, 1),
('Hotel Continental de Roma', 1, 5, 1, 1),
('Hotel Continental de Roma', 1, 5, 2, 1),
('Hotel Continental de Roma', 1, 5, 3, 1),
('Hotel Continental de Roma', 1, 5, 4, 1),
('Hotel Continental de Roma', 1, 5, 5, 1),
('Hotel Continental de Roma', 1, 5, 6, 1),
('Hotel Continental de Roma', 1, 5, 7, 1),
('Hotel Continental de Roma', 1, 5, 8, 1),
('Hotel Continental de Roma', 1, 5, 9, 1),
('Hotel Continental de Roma', 1, 5, 10, 1),
('Hotel Continental de Roma', 2, 1, 1, 1),
('Hotel Continental de Roma', 2, 1, 2, 1),
('Hotel Continental de Roma', 2, 1, 3, 1),
('Hotel Continental de Roma', 2, 1, 4, 1),
('Hotel Continental de Roma', 2, 1, 5, 1),
('Hotel Continental de Roma', 2, 1, 6, 1),
('Hotel Continental de Roma', 2, 1, 7, 1),
('Hotel Continental de Roma', 2, 1, 8, 1),
('Hotel Continental de Roma', 2, 1, 9, 1),
('Hotel Continental de Roma', 2, 1, 10, 1),
('Hotel Continental de Roma', 2, 2, 1, 1),
('Hotel Continental de Roma', 2, 2, 2, 1),
('Hotel Continental de Roma', 2, 2, 3, 1),
('Hotel Continental de Roma', 2, 2, 4, 1),
('Hotel Continental de Roma', 2, 2, 5, 1),
('Hotel Continental de Roma', 2, 2, 6, 1),
('Hotel Continental de Roma', 2, 2, 7, 1),
('Hotel Continental de Roma', 2, 2, 8, 1),
('Hotel Continental de Roma', 2, 2, 9, 1),
('Hotel Continental de Roma', 2, 2, 10, 1),
('Hotel Continental de Roma', 2, 3, 1, 1),
('Hotel Continental de Roma', 2, 3, 2, 1),
('Hotel Continental de Roma', 2, 3, 3, 1),
('Hotel Continental de Roma', 2, 3, 4, 1),
('Hotel Continental de Roma', 2, 3, 5, 1),
('Hotel Continental de Roma', 2, 3, 6, 1),
('Hotel Continental de Roma', 2, 3, 7, 1),
('Hotel Continental de Roma', 2, 3, 8, 1),
('Hotel Continental de Roma', 2, 3, 9, 1),
('Hotel Continental de Roma', 2, 3, 10, 1),
('Hotel Continental de Roma', 2, 4, 1, 1),
('Hotel Continental de Roma', 2, 4, 2, 1),
('Hotel Continental de Roma', 2, 4, 3, 1),
('Hotel Continental de Roma', 2, 4, 4, 1),
('Hotel Continental de Roma', 2, 4, 5, 1),
('Hotel Continental de Roma', 2, 4, 6, 1),
('Hotel Continental de Roma', 2, 4, 7, 1),
('Hotel Continental de Roma', 2, 4, 8, 1),
('Hotel Continental de Roma', 2, 4, 9, 1),
('Hotel Continental de Roma', 2, 4, 10, 1),
('Hotel Continental de Roma', 2, 5, 1, 1),
('Hotel Continental de Roma', 2, 5, 2, 1),
('Hotel Continental de Roma', 2, 5, 3, 1),
('Hotel Continental de Roma', 2, 5, 4, 1),
('Hotel Continental de Roma', 2, 5, 5, 0),
('Hotel Continental de Roma', 2, 5, 6, 0),
('Hotel Continental de Roma', 2, 5, 7, 0),
('Hotel Continental de Roma', 2, 5, 8, 0),
('Hotel Continental de Roma', 2, 5, 9, 0),
('Hotel Continental de Roma', 2, 5, 10, 0);


INSERT INTO Habitaciones (Nombre, Torre, Piso, NumeroHabitacion, Disponibilidad)
VALUES
('Hotel Continental de Osaka Tokyo', 1, 1, 1, 1),
('Hotel Continental de Osaka Tokyo', 1, 1, 2, 1),
('Hotel Continental de Osaka Tokyo', 1, 1, 3, 1),
('Hotel Continental de Osaka Tokyo', 1, 1, 4, 1),
('Hotel Continental de Osaka Tokyo', 1, 1, 5, 1),
('Hotel Continental de Osaka Tokyo', 1, 1, 6, 1),
('Hotel Continental de Osaka Tokyo', 1, 1, 7, 1),
('Hotel Continental de Osaka Tokyo', 1, 1, 8, 1),
('Hotel Continental de Osaka Tokyo', 1, 1, 9, 1),
('Hotel Continental de Osaka Tokyo', 1, 1, 10, 1),
('Hotel Continental de Osaka Tokyo', 1, 2, 1, 1),
('Hotel Continental de Osaka Tokyo', 1, 2, 2, 1),
('Hotel Continental de Osaka Tokyo', 1, 2, 3, 1),
('Hotel Continental de Osaka Tokyo', 1, 2, 4, 1),
('Hotel Continental de Osaka Tokyo', 1, 2, 5, 1),
('Hotel Continental de Osaka Tokyo', 1, 2, 6, 1),
('Hotel Continental de Osaka Tokyo', 1, 2, 7, 1),
('Hotel Continental de Osaka Tokyo', 1, 2, 8, 1),
('Hotel Continental de Osaka Tokyo', 1, 2, 9, 1),
('Hotel Continental de Osaka Tokyo', 1, 2, 10, 1),
('Hotel Continental de Osaka Tokyo', 1, 3, 1, 1),
('Hotel Continental de Osaka Tokyo', 1, 3, 2, 1),
('Hotel Continental de Osaka Tokyo', 1, 3, 3, 0),
('Hotel Continental de Osaka Tokyo', 1, 3, 4, 1),
('Hotel Continental de Osaka Tokyo', 1, 3, 5, 1),
('Hotel Continental de Osaka Tokyo', 1, 3, 6, 1),
('Hotel Continental de Osaka Tokyo', 1, 3, 7, 1),
('Hotel Continental de Osaka Tokyo', 1, 3, 8, 1),
('Hotel Continental de Osaka Tokyo', 1, 3, 9, 1),
('Hotel Continental de Osaka Tokyo', 1, 3, 10, 1),
('Hotel Continental de Osaka Tokyo', 1, 4, 1, 1),
('Hotel Continental de Osaka Tokyo', 1, 4, 2, 1),
('Hotel Continental de Osaka Tokyo', 1, 4, 3, 1),
('Hotel Continental de Osaka Tokyo', 1, 4, 4, 1),
('Hotel Continental de Osaka Tokyo', 1, 4, 5, 1),
('Hotel Continental de Osaka Tokyo', 1, 4, 6, 1),
('Hotel Continental de Osaka Tokyo', 1, 4, 7, 1),
('Hotel Continental de Osaka Tokyo', 1, 4, 8, 1),
('Hotel Continental de Osaka Tokyo', 1, 4, 9, 1),
('Hotel Continental de Osaka Tokyo', 1, 4, 10, 1),
('Hotel Continental de Osaka Tokyo', 1, 5, 1, 1),
('Hotel Continental de Osaka Tokyo', 1, 5, 2, 1),
('Hotel Continental de Osaka Tokyo', 1, 5, 3, 1),
('Hotel Continental de Osaka Tokyo', 1, 5, 4, 1),
('Hotel Continental de Osaka Tokyo', 1, 5, 5, 1),
('Hotel Continental de Osaka Tokyo', 1, 5, 6, 1),
('Hotel Continental de Osaka Tokyo', 1, 5, 7, 1),
('Hotel Continental de Osaka Tokyo', 1, 5, 8, 1),
('Hotel Continental de Osaka Tokyo', 1, 5, 9, 1),
('Hotel Continental de Osaka Tokyo', 1, 5, 10, 1),
('Hotel Continental de Osaka Tokyo', 2, 1, 1, 1),
('Hotel Continental de Osaka Tokyo', 2, 1, 2, 1),
('Hotel Continental de Osaka Tokyo', 2, 1, 3, 1),
('Hotel Continental de Osaka Tokyo', 2, 1, 4, 1),
('Hotel Continental de Osaka Tokyo', 2, 1, 5, 1),
('Hotel Continental de Osaka Tokyo', 2, 1, 6, 1),
('Hotel Continental de Osaka Tokyo', 2, 1, 7, 1),
('Hotel Continental de Osaka Tokyo', 2, 1, 8, 1),
('Hotel Continental de Osaka Tokyo', 2, 1, 9, 1),
('Hotel Continental de Osaka Tokyo', 2, 1, 10, 1),
('Hotel Continental de Osaka Tokyo', 2, 2, 1, 1),
('Hotel Continental de Osaka Tokyo', 2, 2, 2, 1),
('Hotel Continental de Osaka Tokyo', 2, 2, 3, 1),
('Hotel Continental de Osaka Tokyo', 2, 2, 4, 1),
('Hotel Continental de Osaka Tokyo', 2, 2, 5, 1),
('Hotel Continental de Osaka Tokyo', 2, 2, 6, 1),
('Hotel Continental de Osaka Tokyo', 2, 2, 7, 1),
('Hotel Continental de Osaka Tokyo', 2, 2, 8, 1),
('Hotel Continental de Osaka Tokyo', 2, 2, 9, 1),
('Hotel Continental de Osaka Tokyo', 2, 2, 10, 1),
('Hotel Continental de Osaka Tokyo', 2, 3, 1, 1),
('Hotel Continental de Osaka Tokyo', 2, 3, 2, 1),
('Hotel Continental de Osaka Tokyo', 2, 3, 3, 1),
('Hotel Continental de Osaka Tokyo', 2, 3, 4, 1),
('Hotel Continental de Osaka Tokyo', 2, 3, 5, 1),
('Hotel Continental de Osaka Tokyo', 2, 3, 6, 1),
('Hotel Continental de Osaka Tokyo', 2, 3, 7, 1),
('Hotel Continental de Osaka Tokyo', 2, 3, 8, 1),
('Hotel Continental de Osaka Tokyo', 2, 3, 9, 1),
('Hotel Continental de Osaka Tokyo', 2, 3, 10, 1),
('Hotel Continental de Osaka Tokyo', 2, 4, 1, 1),
('Hotel Continental de Osaka Tokyo', 2, 4, 2, 1),
('Hotel Continental de Osaka Tokyo', 2, 4, 3, 1),
('Hotel Continental de Osaka Tokyo', 2, 4, 4, 1),
('Hotel Continental de Osaka Tokyo', 2, 4, 5, 1),
('Hotel Continental de Osaka Tokyo', 2, 4, 6, 1),
('Hotel Continental de Osaka Tokyo', 2, 4, 7, 1),
('Hotel Continental de Osaka Tokyo', 2, 4, 8, 1),
('Hotel Continental de Osaka Tokyo', 2, 4, 9, 1),
('Hotel Continental de Osaka Tokyo', 2, 4, 10, 1),
('Hotel Continental de Osaka Tokyo', 2, 5, 1, 1),
('Hotel Continental de Osaka Tokyo', 2, 5, 2, 1),
('Hotel Continental de Osaka Tokyo', 2, 5, 3, 1),
('Hotel Continental de Osaka Tokyo', 2, 5, 4, 1),
('Hotel Continental de Osaka Tokyo', 2, 5, 5, 1),
('Hotel Continental de Osaka Tokyo', 2, 5, 6, 1),
('Hotel Continental de Osaka Tokyo', 2, 5, 7, 1),
('Hotel Continental de Osaka Tokyo', 2, 5, 8, 0),
('Hotel Continental de Osaka Tokyo', 2, 5, 9, 0),
('Hotel Continental de Osaka Tokyo', 2, 5, 10, 0);



